import { createApiClient, apiOrigin } from './http';
const base = apiOrigin + '/api/auth';
const api = createApiClient();
const post = async (path, body) => (await api.post(base + path, body)).data;
export const register = (body) => post('/register', body);
export const login = (body) => post('/login', body);
export const verifyOtp = (body) => post('/verify-otp', body);
export const resendOtp = (body) => post('/resend-otp', body);
export const forgotPassword = (body) => post('/forgot-password', body);
export const resetPassword = (body) => post('/reset-password', body);
export const reauthenticate = (password) => post('/reauthenticate', { password });
export const contact = (body) => post('/contact', body);
export const getMe = async (options = {}) => (await api.get(base + '/get-me', { ...options, skipAuthNotification: true })).data;
export const logout = () => post('/logout', {});
export const deleteAccount = (confirmation) => post('/delete-account', { confirmation });
export const getGoogleAuthUrl = (link = false) => base + '/google' + (link ? '/link' : '');
