const { Router } = require('express');
const { authUser } = require('../middlewares/auth.middleware');
const validate = require('../middlewares/validate.middleware');
const { createAnalysisSchema } = require('../validations/analysis.validations');
const controller = require('../controllers/analysis.controller');
const resumes = require('../controllers/resume.controller');

const router = Router();
router.use(authUser);
router.post('/analyses', validate(createAnalysisSchema), controller.createAnalysis);
router.post('/analyses/pdf', require('../middlewares/jd-upload.middleware'), controller.createPdfAnalysis);
router.get('/analyses/:analysisId', controller.getAnalysis);
router.get('/analyses/:analysisId/original', controller.downloadOriginal);
router.post('/analyses/:analysisId/requirements/extract', validate(require('zod').z.object({}).strict()), controller.extractRequirements);
router.post('/analyses/:analysisId/requirements/review', validate(require('zod').z.object({}).strict()), controller.reviewRequirements);
router.post('/analyses/:analysisId/resumes', resumes.authorizeAnalysis, require('../middlewares/resume-upload.middleware'), resumes.upload);
router.get('/analyses/:analysisId/resumes', resumes.list);
router.post('/analyses/:analysisId/processing', validate(require('zod').z.object({ retryFailed: require('zod').z.boolean().optional() }).strict()), resumes.startProcessing);
router.get('/analyses/:analysisId/processing', resumes.processingProgress);
router.post('/analyses/:analysisId/resumes/zip', resumes.authorizeAnalysis, require('../middlewares/resume-zip.middleware'), resumes.uploadZip);
module.exports = router;
